export const teamMembers = [
    {
        name: 'Dipak Thapa',
        role: 'CEO & Chief Architect',
        expertise: 'Ecosystem Strategy & Interoperable Infrastructure',
        yearsExp: '11+ yrs Dev',
        healthExp: '9 yrs Digital Health',
        photo: '/team/dipak-thapa.jpg',
        mastery: [
            'Java/Python Enterprise Architecture',
            'HL7 FHIR & OpenHIE Integration',
            'National Health System Design',
        ],
        initials: 'DT',
        highlight: true,
    },
    {
        name: 'Utsav Deshar',
        role: 'Lead EHR Implementer',
        expertise: 'Clinical Workflows & Enterprise Deployment',
        yearsExp: '15 yrs IT',
        healthExp: '6 yrs EHR',
        photo: '/team/utsav-deshar.jpg',
        mastery: [
            'Bahmni & OpenMRS Clinical Reporting',
            'Clinical Workflow Optimization',
            'Metabase & Analytics',
        ],
        initials: 'UD',
    },
    {
        name: 'Madhukar Subedi',
        role: 'Senior UI/UX Architect',
        expertise: 'User-Centric Clinical Design',
        yearsExp: '14+ yrs UI/UX',
        healthExp: 'Healthcare UX',
        photo: '/team/madhukar-subedi.jpg',
        mastery: [
            'Clinical Interface Optimization',
            'Accessibility-First Design',
            'Design System Architecture',
        ],
        initials: 'MS',
    },
    {
        name: 'Alok Subedi',
        role: 'Mobile Architecture Lead',
        expertise: 'High-Performance Mobile Health Infrastructure',
        yearsExp: '11+ yrs Mobile',
        healthExp: 'Remote Health',
        photo: '/team/alok-subedi.jpg',
        mastery: [
            'Native iOS/Android Development',
            'Offline-First Mobile Apps',
            'Rural Health Delivery Systems',
        ],
        initials: 'AS',
    },
    {
        name: 'Sudeep Balchhaudi',
        role: 'Operations & Project Lead',
        expertise: 'Digital Health Lifecycle Management',
        yearsExp: '12+ yrs Web',
        healthExp: 'Odoo Functional',
        photo: '/team/sudeep-balchhaudi.jpg',
        mastery: [
            'Agile Project Delivery',
            'Odoo Functional Consulting',
            'Quality Assurance & Compliance',
        ],
        initials: 'SB',
    },
    {
        name: 'Anish Kumar Yadav',
        role: 'Systems & Compliance Engineer',
        expertise: 'Standards Compliance & ML Integration',
        yearsExp: '3+ yrs IT',
        healthExp: '3 yrs Health',
        photo: '/team/anish-yadav.jpg',
        mastery: [
            'Odoo ERP Implementation',
            'Machine Learning Integration',
            'Health Standards Compliance',
        ],
        initials: 'AY',
        certifications: ['HL7 FHIR', 'HIPAA', 'DHIS2'],
    },
];
